Roi pul342 development
Rocket-Science-Development/pulsar_demo pull request #14
Opened 2023-08-16 21:43 UTC by jananjoy

ROI backend Implementation

2023-08-26 20:45 UTC, rs-aben requested changes
Please change definitions as requested

2023-08-26 20:45 UTC, rs-aben commented on src/roi_backend.py
> +FPR_THRESHOLD = 0.5
These should be as arguments to your function

2023-08-26 20:45 UTC, rs-aben commented on src/roi_backend.py
> +        self.cost_per_FP = 100
These also should be arguments

2023-08-26 20:45 UTC, rs-aben commented on src/roi_backend.py
> +        #Caluclate the True Positive Rate(TPR)
We need False positive rate (FPR) and False negative rate (FNR) to account for errors

FPR = FP/total_positves
FNR = FN/total_negatives

2023-08-26 20:45 UTC, rs-aben commented on src/roi_backend.py
> +        net_FPR = np.sign(FPR_THRESHOLD - TPR) * totalNegatives*self.cost_per_FP
Replace TPR with FPR and TNR with FNR

2023-08-28 01:08 UTC, jananjoy commented on src/roi_backend.py
> +FPR_THRESHOLD = 0.5
Resolved

2023-08-28 01:08 UTC, jananjoy commented on src/roi_backend.py
> +        self.cost_per_FP = 100
Resolved

2023-08-28 01:08 UTC, jananjoy commented on src/roi_backend.py
> +        #Caluclate the True Positive Rate(TPR)
Corrected as below:
The False Positive Rate  FPR = FP / (FP+ TN) 
The False Negative Rate is FNR =  FN/ FN + TP
total_positves =   (FN+TP) being the total number of positives
total_negatives = (FP+ TN)  is the total number of ground truth negatives

2023-08-28 01:09 UTC, jananjoy commented on src/roi_backend.py
> +        net_FPR = np.sign(FPR_THRESHOLD - TPR) * totalNegatives*self.cost_per_FP
Resolved. Changed accordingly

2023-08-29 18:18 UTC, adel-rdccaa requested changes

2023-08-29 18:18 UTC, adel-rdccaa commented on src/roi_backend.py
> +        net_FPR = np.sign(FPR_THRESHOLD - FPR) * totalNegatives * cost_per_FP
You have to multiply net_FPR by the FPR and net_FNR by the FNR. Because right now, You all calculating the total cost for all negatives and the total cost for all positives

2023-09-01 12:28 UTC, jananjoy commented
ROI backend development task in the branch "Roi pul342 development" is copied and integrated in the "ROI changes" branch so I will closed this PR . Other Expanding ROI functionality will be implemented as a new PR request.

2023-09-01 12:28 UTC, jananjoy commented
ROI backend development task in the branch "Roi pul342 development" is copied and integrated in the ROI changes branch so I will closed this PR . Other Expanding ROI functionality will be implemented as a new PR request.

2023-09-01 12:28 UTC, closed without merging